# -*- coding: utf-8 -*-
"""StreamlitNov.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15asZwFOnqBxNn97evThmNwV3_2YWb6kM
"""

import streamlit as st
import joblib
import pandas as pd
# Loại bỏ dòng pip install vì không thể chạy lệnh này trong mã Python

# Tiêu đề ứng dụng
st.title("Ứng dụng Dự đoán Rủi ro Giao hàng Trễ")

# Tải mô hình đã lưu
best_model = joblib.load("best_model.pkl")

# Tạo các ô nhập liệu để người dùng nhập dữ liệu đầu vào
st.header("Nhập thông tin đơn hàng:")
days_for_shipping_real = st.number_input("Days for shipping (real)", min_value=1)
days_for_shipment_scheduled = st.number_input("Days for shipment (scheduled)", min_value=1)
benefit_per_order = st.number_input("Benefit per order")
sales_per_customer = st.number_input("Sales per customer")
order_item_discount = st.number_input("Order Item Discount")
order_item_discount_rate = st.number_input("Order Item Discount Rate")
order_item_product_price = st.number_input("Order Item Product Price")
order_item_profit_ratio = st.number_input("Order Item Profit Ratio")
order_item_quantity = st.number_input("Order Item Quantity", min_value=1)
sales = st.number_input("Sales")

# Nút dự đoán
if st.button("Dự đoán rủi ro giao hàng trễ"):
    # Tạo DataFrame từ dữ liệu đầu vào
    input_data = pd.DataFrame({
        'Days for shipping (real)': [days_for_shipping_real],
        'Days for shipment (scheduled)': [days_for_shipment_scheduled],
        'Benefit per order': [benefit_per_order],
        'Sales per customer': [sales_per_customer],
        'Order Item Discount': [order_item_discount],
        'Order Item Discount Rate': [order_item_discount_rate],
        'Order Item Product Price': [order_item_product_price],
        'Order Item Profit Ratio': [order_item_profit_ratio],
        'Order Item Quantity': [order_item_quantity],
        'Sales': [sales]
    })

    # Thực hiện dự đoán
    prediction =