# -*- coding: utf-8 -*-
"""StreamlitNov.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15asZwFOnqBxNn97evThmNwV3_2YWb6kM
"""

import streamlit as st
import joblib
import pandas as pd

# Kiểm tra xem mô hình đã được tải thành công chưa
try:
    best_model = joblib.load("best_model.pkl")
    st.write("Mô hình đã được tải thành công!")
except FileNotFoundError:
    st.write("Tệp mô hình 'best_model.pkl' không tồn tại!")
except Exception as e:
    st.write(f"Đã có lỗi khi tải mô hình: {e}")

# Tiếp tục với mã của bạn
if 'best_model' in locals():
    # Tạo DataFrame từ dữ liệu đầu vào
    input_data = pd.DataFrame({
        'Days for shipping (real)': [days_for_shipping_real],
        'Days for shipment (scheduled)': [days_for_shipment_scheduled],
        'Benefit per order': [benefit_per_order],
        'Sales per customer': [sales_per_customer],
        'Order Item Discount': [order_item_discount],
        'Order Item Discount Rate': [order_item_discount_rate],
        'Order Item Product Price': [order_item_product_price],
        'Order Item Profit Ratio': [order_item_profit_ratio],
        'Order Item Quantity': [order_item_quantity],
        'Sales': [sales]
    })

    # Dự đoán nếu mô hình đã được tải
    prediction = best_model.predict(input_data)
    if prediction[0] == 1:
        st.write("Kết quả: Có nguy cơ giao hàng trễ.")
    else:
        st.write("Kết quả: Không có nguy cơ giao hàng trễ.")